# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumanage', '0010_auto_bexact_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='short_name',
            field=models.CharField(blank=True, help_text="Institution's shortname/acronym", max_length=10),
        ),
        migrations.AlterField(
            model_name='instserver',
            name='proto',
            field=models.CharField(choices=[('radius', 'traditional RADIUS over UDP'), ('radius-tls', 'RADIUS over TLS (RFC6614)')], default='radius', max_length=12),
        ),
        migrations.AlterField(
            model_name='monproxybackclient',
            name='proto',
            field=models.CharField(choices=[('radius', 'traditional RADIUS over UDP'), ('radius-tls', 'RADIUS over TLS (RFC6614)')], max_length=12),
        ),
    ]
